[project]
name = "Test02"
version = "0.1.0"
output = "bin/test02"
type = "executable" # static(library), shared(library) or executable. (without the content in parentheses)
sources = ["src/**/*.oxy"] # glob pattern for source files. You can also specify individual files like ["src/main.oxy", "src/utils.oxy"]

[modules]
std = "${OXYLIB}/std/std.oxy" # ${VARIABLE} uses environment variables, so you can set OXYLIB (or any other variable) to the desired path before running the build.

[links]
libs = ["m", "raylib"]